### ISSUE TITLE
Cursor's apparent location is ~half a pixel down and to the right of where the actual drawing is happening.

### ISSUE THREAD

**Issue by Tophwells** [increpare/flickgame#15]
![picture](https://i.imgur.com/MudOAc7.png)

Sorry for the JPG artifacts, it was the only tool I had on-hand that does screenshots which show the cursor. Possibly there's a rounding error somewhere in the code.

This isn't usually noticeable, but it does badly interfere with my attempts at pixel-perfect drawing.

**Comment by increpare** [comment]
I guess the target cursor on your operating system is better than mine. One sec...

**Comment by increpare** [comment]
fixed and uploaded. cheers :)

**Comment by Tophwells** [comment]
I wasn't entirely sure, but I found I could dial up the `zoomFactor` setting until the pixels were several centimetres across. That let me test it properly.
