### ISSUE TITLE
Layers version: An else of an if with a nested if in it works in editor but not in exported file

### ISSUE THREAD

**Issue by Norgg** [increpare/flickgame#32]
Minimal example [here](http://norgg.org/files/nested_else.html), if you import and press the button while testing in the editor it shows 7, but in the exported file nothing happens. All the other code paths seem to work fine.

Tested in Chrome.

**Comment by Norgg** [comment]
More complex thing I was making where I noticed this: https://www.flickgame.org/layers_beta.html?p=055b46dbbd47aa13fba7a7536d7f5352

**Comment by increpare** [comment]
ah good catch, if you force reload, it should be fixed now?

2018-06-29 23:19 GMT+02:00 Norgg <notifications@github.com>:

**Comment by Norgg** [comment]
Yeah, fixed. Thanks!

**Comment by increpare** [comment]
thank you for the report!

2018-06-29 23:35 GMT+02:00 Norgg <notifications@github.com>:
